# Site settings
name: Juconcurrent
email: zhangfb95@aliyun.com
author: zhangfb95
url: http://open.juconcurrent.com
resume_site: nothing here
github: https://github.com/zhangfb95/
baseurl: "/"
description: Juconcurrent, Nice to meet you!
meta_description: 付兵;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto:
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: zhangfb95

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

